### ISSUE TITLE
Actualización de SHA1 a SHA-256

### ISSUE THREAD

**Issue by luisphi** [placetopay/java-placetopay#1]
En código de este proyecto esta para realizar la autenticación se está usando SHA1:  
byte[] digest = Utils.sha1(this.getNonce(false)+this.getSeed()+this.tranKey); 

Sin embargo en la documentación se está solicitado que se realice con SHA-256, 
# Base64(SHA-256(nonce + seed + tranKey))

Tienen fecha de actualización para este proyecto bajo las nuevas normas de seguridad?

**Comment by placetopay** [comment]
Por favor, envíame la documentación en donde aparece que es SHA256 al correo desarrollo@placetopay.com para validar

**Comment by dnetix** [comment]
Hola Luis
No se tiene programado modificar el SHA que se está usando actualmente, es y seguirá siendo SHA1 al menos para esta versión del API. Es posible que se cambie en un nuevo lanzamiento pero no hay fecha para ello.
El único manual para Redirección es el M-TEC-216, se han creado servicios nuevos que vienen con SHA-256 para la autenticación pero son diferentes.

**Comment by luisphi** [comment]
Hola Diego
Estoy en el manual para integración por servicios web M-TEC-300 (Te lo envié al correo), y para la autenticación estoy usando parte del código que se está usando en este proyecto de git. 

Gracias

**Comment by dnetix** [comment]
Hola Luis, no sabia que eras vos. Efectivamente este repositorio está hecho para conectarse al servicio de Redirección, pero lo que te explique y como entendí que se van a conectar es a través del API del webservice de tarjetas en Ecuador y no por redirección.

Lamentablemente para el servicio que vas a hacer la conexión no hay un SDK público, las empresas que se conectan directo al webservice (M-TEC-300) generalmente hacen su propio SDK. Esta solución es diferente, si quieres te explico como funciona, pero no creo que sea útil para vos porque ustedes necesitan el número de tarjeta y este servicio lo que hace es quitar la responsabilidad del manejo de la tarjeta a los clientes.

**Comment by luisphi** [comment]
Que tal. Si te entiendo, lo único que quiero es usar parte del código de esta clase para la Authentication, https://github.com/placetopay/java-placetopay/blob/master/src/main/java/com/placetopay/java_placetopay/Carrier/Authentication.java

El resto efectivamente lo vamos a a realizar nosotros, pero quería saber si lo puedo usar por el tema de los SHA

**Comment by dnetix** [comment]
Si lo podría usar, es muy similar en la autenticación, ps obviamente cambiando el SHA-1 por un SHA-256
